landmark_choices = {
    '1': 'Marine Building',
    '2': 'Scotiabank Field at Nat Bailey Stadium',
    '3': 'Vancouver Aquarium',
    '4': 'Vancouver Lookout',
    '5': 'Canada Place',
    '6': 'Cathedral of Our Lady of the Holy Rosary',
    '7': 'Library Square',
    '8': 'B.C. Place Stadium',
    '9': 'Lions Gate Bridge',
    '10': 'Gastown Steam Clock',
    '11': 'Waterfront Station',
    '12': 'Granville Street',
    '13': 'Prospect Point Lighthouse',
    '14': 'Queen Elizabeth Theatre',
    '15': 'Stanley Park',
    '16': 'Granville Island Public Market',
    '17': 'Kitsilano Beach',
    '18': 'Dr. Sun Yat-Sen Classical Chinese Garden',
    '19': 'Museum of Vancouver',
    '20': 'Science World',
    '21': 'Robson Square',
    '22': 'Samson V Maritime Museum',
    '23': 'Burnaby Lake',
    '24': 'Nikkei National Museum & Cultural Centre',
    '25': 'Central Park',
    '26': 'Pacific Central Station',
}